[profile.default]
src = "src/pages"
out = "out"
libs = ["forge-lib"]
test = "forge-test"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
evm_version = "cancun"
solc_version = "0.8.24"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config