[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
cancun = true

# For Linux/WSL2 systems, please change to `lib/v4-core/bin/solc-static-linux`
solc = "lib/v4-core/bin/solc-mac"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config